FROM mcr.microsoft.com/azure-cli AS cli-base

ARG BUNDLE_DIR

RUN apk update
RUN apk add -u bash

# Install any needed packages specified in requirements.txt
RUN az extension add --name azure-cli-iot-ext

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR



